### ISSUE TITLE
Add volume support for better user experience

### ISSUE THREAD

**Issue by swatisehgal** [openshift/secondary-scheduler-operator#11]
For a better user experience and freeing users from configuring too many technical details, we should add volume support in this operator to allow the scheduler plugins to be created with necessary volumes.

**Comment by damemi** [comment]
This could be done a couple of ways, but I think the most operator-oriented way that we discussed would be to have a field in the CRD to specify a list of volumes and the paths they should be mounted to in the scheduler deployment.

ie,
```
spec:
  ...
  volumes:
    - name: xyz
      hostPath: /local/dir
      mountPath: /dir/foo
```

which would be translated in the deployment to

```
spec:
  containers:
  ...
    volumeMounts:
    - name: xyz
      mountPath: /dir/foo
  volumes:
  - name: xyz
    hostPath:
      path: /local/dir
```

the question is how many different kinds of volume mounts do we support? Just hostpath and PVCs is reasonable enough, but that also requires some way to tell the operator to differentiate between them.

@swatisehgal could you include more specific details about the use case for volume mounts?

**Comment by swatisehgal** [comment]
The way you have it in the example above with hostpath satisfies our use case perfectly.  In case of hostpath we would need an additional field `hostPathType` to specify the type as has been detailed [here](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath). I agree that it makes sense to handle PVC in addition to hostpath. My suggestion would be have a `type` field to indicate whether it is PVC or hostPath. Also, I propose that instead of having a `hostPath` field we could have a generic field `source` (or a descriptive) field which in case of hostPath volumes would be used to specify the path of the file/directory and in case of PVC would be used to specify the `claimName`. Having said that, if you think that is confusing we can have two separate fields `hostPath` and `claimName`. Here is how the CRD spec could look like in both these cases:
```
spec:
  ...
  volumes:
    - name: xyz
      type: hostPath
      source: /local/dir
      hostPathType: Directory # valid values of this field would be Directory/File/FileOrCreate/DirectoryOrCreate/Socket/CharDevice/BlockDevice
      mountPath: /dir/foo
```
In case of PVCs, it would look like this:
```
spec:
  ...
  volumes:
    - name: xyz
      type: pvc
      source: <claimName>
      mountPath: /dir/foo
```

We should make sure we consider access modes here too. I think we don't need them as HostPath is only mounted as readOnly and in PVC the access modes are specified in the PersistentVolumeClaim definition but lets be 100% sure.
