### ISSUE TITLE
Automation to support scheduler plugin parameter/manifest changes based on scheduler plugin user configurations

### ISSUE THREAD

**Issue by swatisehgal** [openshift/secondary-scheduler-operator#12]
There could be scenarios where based on the user configuration specified in the scheduler config the parameters of the scheduler plugin deployment file or RBAC rules associated with the scheduler plugin/scheduler plugin operator needs to be changed and it would be beneficial to provide a mechanism to handle that. 

Here is a scenario:
In case of Noderesourcetopology scheduler plugin the scheduler config looks like below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: topo-aware-scheduler-config
  namespace: openshift-secondary-scheduler-operator
data:
  config.yaml: |
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: KubeSchedulerConfiguration
      leaderElection:
        leaderElect: false
      clientConnection:
        kubeconfig:  ${KUBECONFIG_PATH}
      profiles:
        - schedulerName: topo-aware-scheduler
          plugins:
            filter:
              enabled:
                - name: NodeResourceTopologyMatch
            score:
              enabled:
                - name: NodeResourceTopologyMatch
          # optional plugin configs
          pluginConfig:
          - name: NodeResourceTopologyMatch
            args:
              kubeconfigpath: ${KUBECONFIG_PATH}
              namespaces:
              - "default"
```

The pluginConfig section has a namespace field which is used to specify the namespace watched by the scheduler plugin  for obtaining `NodeResourceTopology` CR instances. Based on the namespace(s) configured RBAC rules for NRT CR access would vary.
