### ISSUE TITLE
Add support to Always pull image

### ISSUE THREAD

**Issue by tedhtchang** [openshift/secondary-scheduler-operator#505]
Add support to Always pull image
```
apiVersion: operator.openshift.io/v1
kind: SecondaryScheduler
metadata:
  name: xxx
spec:
  ...
  imagePullPolicy: Always
```
